#' Summary label/annotation records for volume
#'
#' Visualize label/annotation count as a bar chart in this volume.
#'
#' @param volName Volume name.
#' @param countLimit (OPTIONAL) Exclude the label/annotation records that count less than the limit (int). Default: 0.
#' @param haveReport TRUE or FALSE. Already have the reports or not.\cr
#' If FALSE, \cr input need input parameters: \code{url}, \code{auth}, \code{downloadFolder}, \code{waitingTime}; it can automatically call \code{\link{reqNgetRep}} to prepare volume's reports. \cr
#' If TRUE, \cr input the report: \code{labelReport} and \code{annotationReport}.
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param downloadFolder The directory path to save the downloaded report files.
#' @param waitingTime (OPTIONAL) Waiting time (in sec.)for server to generate the report. Default: 5 sec.
#' @param labelReport The label report table.
#' @param annotationReport The annotation report table.
#' @examples
#' \dontrun{
# ana_sumVol(volName = "TTC19",
#'            countLimit = 20,
#            haveReport = TRUE,
#            labelReport = ex_label,
#            annotationReport =  ex_annotation)
#' ana_sumVol(volName = "TTC19",
#'            countLimit = 20,
#'            haveReport = FALSE,
#'            url = "https://seaimage.oc.ntu.edu.tw",
#'            auth = myAuth,
#'            downloadFolder = "C:\\tmp\\odbiigleT\\tmp",
#'            waitingTime = 5)
#' }
#' @export
ana_sumVol <- function(volName, countLimit = 0, haveReport
                       , url = NULL, auth = NULL, downloadFolder = NULL, waitingTime = 5
                       , labelReport = NULL, annotationReport = NULL){
  if(!haveReport){
    reqNgetRep(url, auth, volName, "a", downloadFolder, folderName = "annotation", waitingTime)
    reqNgetRep(url, auth, volName, "l", downloadFolder, folderName = "label", waitingTime)
    annotationReport <- file.path(downloadFolder, "annotation") %>% readFiles
    labelReport <- file.path(downloadFolder, "label") %>% readFiles
  }
  allLabs <- rbind(labelReport[,.(label_id, label_name)], annotationReport[,.(label_id, label_name)]) %>% unique
  imgNo <- c(labelReport$filename, annotationReport$filename) %>% unique %>% length
  # LABEL
  # label analysis
  labC <- labelReport[,.N,label_id] %>%
    merge(., allLabs, by = "label_id", all.x = TRUE) %>%
    .[N > countLimit]
  # bar plot
  pl <- ggplot(labC, aes(x=reorder(label_name, N), y = N)) +
    coord_flip()+
    theme_bw()+
    geom_bar(stat = "identity", fill = "#125E98")+
    labs(title = "Label count"
         ,x = NULL
         ,y = "count")
  # ANNOTATION
  # annotation analysis
  annoC <- annotationReport[,.N,label_id] %>%
    merge(., allLabs, by = "label_id", all.x = TRUE) %>%
    .[N > countLimit]
  # bar plot
  pa <- ggplot(annoC, aes(x=reorder(label_name, N), y = N)) +
    coord_flip()+
    theme_bw()+
    geom_bar(stat = "identity", fill = "#12988F")+
    labs(title = "Annotation count"
         ,x = NULL
         ,y = "count")
  # COMBINE
  figure <- ggarrange(pa, pl, ncol = 1, nrow = 2, align = "v")
  annotate_figure(figure,
                  top = text_grob(color = "Black", face = "bold", size = 14,
                                  label = paste0("Summary for ", volName)),
                  bottom = text_grob(color = "#3D3D3D", size = 10,
                                     label = paste0("There are ",
                                                    nrow(labelReport), " label-records and ",
                                                    nrow(annotationReport), " annotation-records in ",
                                                    imgNo, " images.")))
}
