#' biigler
#'
#' `biigler` is an unofficial R package developed by Underwater Image Identification Working Group in ODB, IONTU, mainly for substituting the repetitive operations on the BIIGLE 2.0 graphical user interface.
#' It is based on BIIGLE v3.14.2 and R v4.1.2.
#'
#' @docType package
#' @name biigler
NULL


#' @import data.table
#' @import progress
#' @import httr
#' @import ggplot2
#' @importFrom magrittr %>%
#' @importFrom jsonlite base64_enc
#' @importFrom jsonlite fromJSON
#' @importFrom ggpubr ggarrange
#' @importFrom ggpubr annotate_figure
#' @importFrom ggpubr text_grob
NULL


#' Get information on BIIGLE server.
#'
#' Get information on BIIGLE server, including basic volume ID, label tree information, and so on.
#'
#' @section
#' Functions:
#' * `genAuth` Generate the string for BIIGLE API authentication.\cr
#' * `getTree` Get all label's information in the label tree through tree ID.\cr
#' * `getVolID` Get volume ID through volume name.\cr
#' * `getVolImg` Get all image's information in the volume.\cr
#' * `reqNgetRep` Request BIIGLE server to generate a volume report (csv type) and download it.\cr
#' * `readFiles` Read all reports in the folder and bind as one table.\cr
#' @docType package
#' @name getBIIGLE
NULL


#' Generate Authentication String
#'
#' Generate the string for BIIGLE API authentication. Use it wherever the function needs to interact with BIIGLE API (function with the parameter `auth`).\cr
#' NOTE: You need input the API token which can be created by: BIIGLE server > Settings > Tokens > Generate.
#'
#' @param account Your BIIGLE account (email you sign-in for BIIGLE).
#' @param apiToken Your BIIGLE API token.
#' @examples
#' \dontrun{
#' forAuth <- genAuth(account = "myBiigleAccount@email.com",
#'                    apiToken = "myAPItoken")
#' }
#' @details See more details on \href{https://biigle.de/doc/api/index.html}{BIIGLE RestfulAPI manual}.
#' @export
genAuth <- function(account, apiToken){
  paste0("Basic ", base64_enc(paste0(account, ":", apiToken)))
}


#' Get Label Tree
#'
#' Get all label's information in the label tree through tree ID.
#'
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param treeID Label tree ID.
#' @examples
#' \dontrun{
#' catamiTree <- getTree(url = "https://seaimage.oc.ntu.edu.tw",
#'                       auth = myAuth,
#'                       treeID = 5)
#' }
#' @export
getTree <- function(url, auth, treeID){
  res <- GET(url = paste0(url, "/api/v1/label-trees/", treeID)
             , add_headers(Accept = "application/json"
                           ,Authorization = auth))
  if(res$status_code != 200){
    stop("Authentication failed.\nPlease check your token is correct and authenticated to access this volume.")
  }else{
    defaultw <- getOption("warn")
    options(warn = -1)
    output <- rbindlist(content(res)$label, use.names = T, fill = T)
    options(warn = defaultw)
    return(output)
  }
}


#' Get Volume ID
#'
#' Get volume ID through volume name.
#' NOTE: The volume name must be unique on BIIGLE server, otherwise it cannot know which volume you are interested with.
#'
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param volName Volume name on BIIGLE that you interested in.
#' @examples
#' \dontrun{
#' volID <- getVolID(url = "https://seaimage.oc.ntu.edu.tw",
#'                   auth = myAuth,
#'                   volName = "TTC17")
#' }
#' @export
getVolID <- function(url, auth, volName){
  res <- GET(url = paste0(url, "/api/v1/volumes/")
             , add_headers(Accept = "application/json"
                           ,Authorization = auth))
  if(res$status_code != 200){
    stop("Authentication failed.\nPlease check your token is correct and authenticated to access this volume.")
  }else{
    defaultw <- getOption("warn")
    options(warn = -1)
    volList <- rbindlist(content(res), use.names = T) %>% .[name == volName]
    options(warn = defaultw)
    if(nrow(volList) == 0){
      stop("No match volume, please check volume name.")
    }else if(nrow(volList) == 1){
      return(volList[name == volName]$id)
    }else{
      stop("The input volume name is NOT unique on this server, failed to set volume.")
    }
  }
}


#' Get Image's information in Volume
#'
#' Get all image's information in the volume (a table with column "imageID" and "filename").
#'
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param vol Volume ID (integer) or name (character). Volume's ID can get by \code{\link{getVolID}}.
#' @examples
#' \dontrun{
#' imgList_ttc17 <- getVolImg(url = "https://seaimage.oc.ntu.edu.tw",
#'                            auth = myAuth,
#'                            vol = 5)
#' imgList_ttc17 <- getVolImg(url = "https://seaimage.oc.ntu.edu.tw",
#'                            auth = myAuth,
#'                            vol = "TTC17")
#' }
#' @export
getVolImg <- function(url, auth, vol){
  volID <- switch (class(vol),
                   numeric = vol,
                   character = getVolID(url, auth, vol),
                   stop("Invalid 'vol' input. Please enter volume's ID (integer) or name (character)"))
  res <- GET(url = paste0(url, "/api/v1/volumes/", volID,"/filenames")
             , add_headers(Accept = "application/json"
                           ,Authorization = auth))
  if(res$status_code != 200){
    stop("Authentication failed.\nPlease check your token is correct and authenticated to access this volume.")
  }else{
    output <- data.table(imageID = attributes(content(res))$name,
                         filename = content(res) %>% unlist %>% as.vector())
    return(output)
  }
}


#' Request and Download BIIGLE Report
#'
#' Request BIIGLE server to generate a label/annotation report (limited for 'csv' type) and download it.
#'
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param vol Volume ID (int) or name (char). Volume ID can get by \code{\link{getVolID}}.
#' @param reportType Input 'a' for annotation report or 'l' for label report (only return 'csv' type report).
#' @param downloadFolder The directory path to save the downloaded report files.
#' @param folderName (OPTIONAL) Customize directory name for downloaded report. Default: "biigle_report".
#' @param waitingTime (OPTIONAL) Waiting time (in sec.) for server to generate the report. Default: 5 sec.
#' @examples
#' \dontrun{
#' reqNgetRep(url = "https://seaimage.oc.ntu.edu.tw",
#'             auth = myAuth,
#'             vol = "test_exam_answer",
#'             reportType = "a",
#'             downloadFolder = "C:\\tmp\\test",
#'             folderName = "biigle_report",
#'             waitingTime = 5)
#' }
#' @export
reqNgetRep <- function(url, auth, vol, reportType
                       # , seperateTrees = TRUE
                       , downloadFolder, folderName = "biigle_report", waitingTime = 5){
  volID <- switch (class(vol),
                   numeric = vol,
                   character = getVolID(url, auth, vol),
                   stop("Invalid 'vol' input. Please enter volume's ID (integer) or name (character)"))
  reportTypeID <- switch (tolower(reportType),
                          a = 3,
                          l = 7,
                          stop("Invalid 'reportType' input. Please enter 'a' (annotation) or 'l' (label)."))
  # seperateTreesB <- ifelse(seperateTrees, "true", "false")
  message("Requesting report...")
  res <- POST(url = paste0(url, "/api/v1/volumes/", volID, "/reports")
               , add_headers(Accept = "application/json"
                             ,Authorization = auth)
               , body = list(type_id = reportTypeID
                             # ,separateLabelTrees = seperateTreesB
                             ))
  if(res$status_code == 201){
    message("Wait for preparing report...")
  }else{
    message("Something wrong during requesting report. Server response: ")
    return(res)
  }
  Sys.sleep(waitingTime)
  res2 <- GET(url = paste0(url ,"/api/v1/reports/", content(res)$id),
                add_headers(Accept = "application/json", Authorization = auth))
  if(res2$status_code != 200){
    message("Download failed. Bad server response, auto-retrying...")
    message("Wait for preparing report...")
    Sys.sleep(waitingTime)
    res2_2 <- GET(url = paste0(url, "/api/v1/reports/", content(res)$id),
                  add_headers(Accept = "application/json", Authorization = auth))
    if(res2_2$status_code != 200){
      message("Download failed. Please download report from BIIGLE server or adjust waiting time.")
      return(c(res2, res2_2))
    }
  }
  GET(url = paste0(url, "/api/v1/reports/", content(res)$id),
      add_headers(Accept = "application/json", Authorization = auth),
      write_disk(paste0(file.path(downloadFolder, folderName), ".zip")))
  unzip(paste0(file.path(downloadFolder, folderName), ".zip"), exdir = file.path(downloadFolder, folderName))
  message("Download report succeed.")
}


#' Read all reports in folder and bind as one table
#'
#' Some volume's report separated by different tree, read all of them as one table.
#'
#' @param folderPath The directory path to read all report files.
#' @examples
#' \dontrun{
#' ttc17 <- readFiles(folderPath = "C:\\tmp\\odbiigleT\\5_csv_image_annotation_report")
#' }
#' @export
readFiles <- function(folderPath){
  allRec <- lapply(list.files(folderPath), function (x) fread(file.path(folderPath, x))) %>% rbindlist
  return(allRec)
}

