#' Labeling Assistant
#'
#' Post massive label combination on images through BIIGLE API.\cr
#' It achieve with a set of functions, following 3 steps:
#' 1. `setVol` Set working volume. It only need to run 1 times for a R session.
#' 2. `setShortcut` Create the label combination (shortcut) to post on images.
#' 3. `postLabs` or `delLabs` Post/Delete specific label combination (shortcut) on images in filename order.
#'
#' @docType package
#' @name labelingAssistant
NULL


#' Set working volume
#'
#' A function of "Labeling Assistant".\cr
#' It will create two needed tables "allLabs" and "imgList" in global environment.
#'
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param vol Volume ID (int) or name (char). Volume's ID can get by \code{\link{getVolID}}.
#' @param treeIDs Label trees  that need to use in this volume (vector with integer).
#' @examples
#' \dontrun{
#' setVol(url = "https://seaimage.oc.ntu.edu.tw",
#'        auth = myAuth,
#'        vol = "TTC17",
#'        treeIDs = c(5, 8, 9, 14, 15))
#' }
#' @export
setVol <- function(url, auth, vol, treeIDs){
  getVolImg(url, auth, vol) %>%
    assign("imgList", ., envir = .GlobalEnv)
  lapply(treeIDs, function(x) getTree(url, auth, treeID = x)) %>%
    rbindlist(.) %>%
    assign("allLabs", ., envir = .GlobalEnv)
  if(all(c("allLabs","imgList") %in% ls(envir = .GlobalEnv))){
    message("Set volume ", vol," succeed.")
  }else{
    message("Something wrong. Set volume failed.")
  }
}


#' Set shortcut (label combination)
#'
#' A function of "Labeling Assistant".\cr
#' Create the label combination (shortcut) to post on images.\cr
#' NOTE: Need to \code{\link{setVol}} first!
#'
#' @param x A label name vector.
#' @examples
#' \dontrun{
#' setVol(url = "https://seaimage.oc.ntu.edu.tw",
#'        auth = myAuth,
#'        vol = "TTC17",
#'        treeIDs = c(5, 8, 9, 14, 15)) # only need to run 1 time
#' sho1 <- setShortcut(c("Flat", "Sand / mud (<2mm)", "Bioturbated"))
#' shoDL <- setShortcut("done_labelling")
#' }
#' @export
setShortcut <- function(x){
  if(!("allLabs" %in% ls(envir = .GlobalEnv))){
    stop("Please assign the volume you going to work with (by setVol) first.")
  }
  label_id <- NULL
  for (i in seq_along(x)) {
    id <- allLabs[name == x[i]]$id
    if(length(id) == 1){
      label_id <- c(label_id, id)
    }else if(length(id) > 1){
      stop("Input label name is not unique, cannot check its ID. Please see label: ", x[i])
    }else if(length(id) == 0){
      stop("No match label name for: ", x[i],"\nPlease check the spelling or label tree version.")
    }else{
      stop("Something wrong. Set shorcut failed.")
    }
  }
  return(label_id)
}


#' Post label combination for images in filename order
#'
#' A function of "Labeling Assistant".\cr
#' Post specific label combination (shortcut) on images IN `filename` ORDER! Hence, DO NOT use "Random" to sort files on BIIGLE, otherwise you may misleading yourself which image you are going to post labels.\cr
#' NOTE: Need to \code{\link{setVol}} and \code{\link{setShortcut}} first!
#'
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param imgStart The start image's filename.
#' @param imgEnd The end image's filename (If only 1 image to label, set the same as the `imgStart`).
#' @param shortcut The shortcut vector generated by \code{\link{setShortcut}}.
#' @examples
#' \dontrun{
#' setVol(url = "https://seaimage.oc.ntu.edu.tw",
#'        auth = myAuth,
#'        vol = "odbiigle",
#'        treeIDs = 5) # only need to run 1 time
#' sho1 <- setShortcut(c("Flat", "Sand / mud (<2mm)", "Bioturbated"))
#' postLabs(url = "https://seaimage.oc.ntu.edu.tw",
#'          auth = myAuth,
#'          imgStart = "2006_10_07_16_29_30.jpg",
#'          imgEnd = "2006_10_07_16_29_50.jpg",
#'          shortcut = sho1)
#' }
#' @export
postLabs <- function(url, auth, imgStart, imgEnd, shortcut){
  if(!("imgList" %in% ls(envir = .GlobalEnv))){
    stop("Please set volume (by setVol) before labeling.")
  }
  if(!all(c(imgStart, imgEnd) %in% imgList$filename)){
    stop("Cannot find input image in this volume. Please check image name is correct and setVol succeed.")
  }
  message("You are going to add labels:\n", paste0(allLabs[id %in% shortcut]$name, collapse = ", "), "\nFor images:\n", imgStart, " ~ ", imgEnd)
  if(readline(prompt = "Are you sure to do that? (y/n)") == "y"){
    t1=Sys.time()
    message("Labeling start...")
    targetImgID <- imgList$imageID[which(imgList$filename == imgStart):which(imgList$filename == imgEnd)]
    pb <- progress_bar$new(format = "(:spin) [:bar] :percent [Elapsed time: :elapsedfull || Estimated time remaining: :eta]",
                           total = length(targetImgID))
    failed <- NULL
    for (i in seq_along(targetImgID)) {
      for (j in seq_along(shortcut)) {
        res <- postALab(url, auth, targetImgID[i], shortcut[j])
        if(!is.null(res)){
          failed <- rbind(failed, data.table(imageFailed = imgList[imageID == res$imageFailed]$filename,
                                             labelFailed = allLabs[id == res$labelFailed]$name))
        }
      }
      pb$tick()
    }
    t2=Sys.time()
    message("\nLabeling done. [Consumimg time: ", difftime(t2,t1, units = "min") %>% round(.,2), " min]")
    if(length(failed != 0)){
      message("Result: Some labeling failed, please check the bellowing failed list.")
      return(failed)
    }else{
      message("Result: Labeling all succeed.")
    }
  }else{
    message("Labeling canceled.")
  }
}


#' Delete label combination for images in filename order
#'
#' A function of "Labeling Assistant".\cr
#' Delete specific labels combination on images IN `filename` ORDER! Hence, DO NOT use "Random" to sort files on BIIGLE, otherwise you may misleading yourself which image's label you are going to delete.\cr
#' NOTE: Need to \code{\link{setVol}} and \code{\link{setShortcut}} first!
#'
#' @param url BIIGLE server URL (e.g. "https://seaimage.oc.ntu.edu.tw").
#' @param auth Authentication string generated by \code{\link{genAuth}}.
#' @param imgStart The start image's filename.
#' @param imgEnd The end image's filename (If only 1 image to delete, set the same as the `imgStart`).
#' @param shortcut The shortcut vector that generate by \code{\link{setShortcut}}.
#' @examples
#' \dontrun{
#' setVol(url = "https://seaimage.oc.ntu.edu.tw",
#'        treeIDs = 5,
#'        auth = myAuth,
#'        vol = "odbiigle") # only need to run 1 time
#' sho1 <- setShortcut(c("Flat"))
#' delLabs(url = "https://seaimage.oc.ntu.edu.tw",
#'         auth = myAuth,
#'         imgStart = "2006_10_07_16_29_30.jpg",
#'         imgEnd = "2006_10_07_16_29_50.jpg",
#'         shortcut = sho1)
#' }
#' @export
delLabs <- function(url, auth, imgStart, imgEnd, shortcut){
  if(!("imgList" %in% ls(envir = .GlobalEnv))){
    stop("Please assign the volume you going to delete for (by setVol) before deletion.")
  }
  if(!all(c(imgStart, imgEnd) %in% imgList$filename)){
    stop("Cannot find input image in this volume. Please check the image filename correct and setVol succeed.")
  }
  message("You are going to delete labels:\n", paste0(allLabs[id %in% shortcut]$name, collapse = ", "), "\nFor images:\n", imgStart, " ~ ", imgEnd)
  if(readline(prompt = "Are you sure to do that? (y/n)") == "y"){
    t1=Sys.time()
    message("Deletion start...")
    targetImgID <- imgList$imageID[which(imgList$filename == imgStart):which(imgList$filename == imgEnd)]
    pb <- progress_bar$new(format = "(:spin) [:bar] :percent [Elapsed time: :elapsedfull || Estimated time remaining: :eta]",
                           total = length(targetImgID))
    failed <- NULL
    for (i in seq_along(targetImgID)) {
      labsOnimg <- GET(url = paste0(url, "/api/v1/images/", targetImgID[i],"/labels")
                       , add_headers(Accept = "application/json"
                                     ,Authorization = auth)) %>% content
      if(length(labsOnimg) != 0){
        for (j in 1:length(labsOnimg)) {
          if(labsOnimg[[j]]$label_id %in% shortcut){
            delRes <- delALab(url, auth, labsOnimg[[j]]$id)
            if(!delRes){
              failed <- rbind(failed, data.table(imageFailed = imgList[imageID == targetImgID[i]]$filename,
                                                 labelFailed = allLabs[id == labsOnimg[[j]]$label_id]$name))
            }
          }
        }
      }
      pb$tick()
    }
    t2=Sys.time()
    message("\nDeletion done. [Consumimg time: ", difftime(t2,t1, units = "min") %>% round(.,2), " min]")
    if(length(failed != 0)){
      message("Result: Some deletion failed, please check the bellowing failed list (note: it may be because image exist with the label NOT added by you, so you don't have permission to delete it).")
      return(failed)
    }else{
      message("Result: Deletion all succeed.")
    }
  }else{
    message("Deletion canceled.")
  }
}
